/*
 * Generated by gdbus-codegen 2.54.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __AGENT1_H__
#define __AGENT1_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.bluez.Agent1 */

#define TYPE_ORG_BLUEZ_AGENT1 (org_bluez_agent1_get_type ())
#define ORG_BLUEZ_AGENT1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_AGENT1, OrgBluezAgent1))
#define IS_ORG_BLUEZ_AGENT1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_AGENT1))
#define ORG_BLUEZ_AGENT1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_BLUEZ_AGENT1, OrgBluezAgent1Iface))

struct _OrgBluezAgent1;
typedef struct _OrgBluezAgent1 OrgBluezAgent1;
typedef struct _OrgBluezAgent1Iface OrgBluezAgent1Iface;

struct _OrgBluezAgent1Iface
{
  GTypeInterface parent_iface;

  gboolean (*handle_authorize_service) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device,
    const gchar *arg_uuid);

  gboolean (*handle_cancel) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_display_passkey) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device,
    guint arg_passkey,
    guint16 arg_entered);

  gboolean (*handle_display_pin_code) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device,
    const gchar *arg_pincode);

  gboolean (*handle_release) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_request_authorization) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device);

  gboolean (*handle_request_confirmation) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device,
    guint arg_passkey);

  gboolean (*handle_request_passkey) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device);

  gboolean (*handle_request_pin_code) (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_device);

};

GType org_bluez_agent1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_bluez_agent1_interface_info (void);
guint org_bluez_agent1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_bluez_agent1_complete_release (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

void org_bluez_agent1_complete_request_pin_code (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *response);

void org_bluez_agent1_complete_display_pin_code (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

void org_bluez_agent1_complete_request_passkey (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation,
    guint reply);

void org_bluez_agent1_complete_display_passkey (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

void org_bluez_agent1_complete_request_confirmation (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

void org_bluez_agent1_complete_request_authorization (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

void org_bluez_agent1_complete_authorize_service (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);

void org_bluez_agent1_complete_cancel (
    OrgBluezAgent1 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void org_bluez_agent1_call_release (
    OrgBluezAgent1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_release_finish (
    OrgBluezAgent1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_release_sync (
    OrgBluezAgent1 *proxy,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_request_pin_code (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_request_pin_code_finish (
    OrgBluezAgent1 *proxy,
    gchar **out_response,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_request_pin_code_sync (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    gchar **out_response,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_display_pin_code (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    const gchar *arg_pincode,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_display_pin_code_finish (
    OrgBluezAgent1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_display_pin_code_sync (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    const gchar *arg_pincode,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_request_passkey (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_request_passkey_finish (
    OrgBluezAgent1 *proxy,
    guint *out_reply,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_request_passkey_sync (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    guint *out_reply,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_display_passkey (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    guint arg_passkey,
    guint16 arg_entered,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_display_passkey_finish (
    OrgBluezAgent1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_display_passkey_sync (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    guint arg_passkey,
    guint16 arg_entered,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_request_confirmation (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    guint arg_passkey,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_request_confirmation_finish (
    OrgBluezAgent1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_request_confirmation_sync (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    guint arg_passkey,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_request_authorization (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_request_authorization_finish (
    OrgBluezAgent1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_request_authorization_sync (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_authorize_service (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    const gchar *arg_uuid,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_authorize_service_finish (
    OrgBluezAgent1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_authorize_service_sync (
    OrgBluezAgent1 *proxy,
    const gchar *arg_device,
    const gchar *arg_uuid,
    GCancellable *cancellable,
    GError **error);

void org_bluez_agent1_call_cancel (
    OrgBluezAgent1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_bluez_agent1_call_cancel_finish (
    OrgBluezAgent1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_bluez_agent1_call_cancel_sync (
    OrgBluezAgent1 *proxy,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_BLUEZ_AGENT1_PROXY (org_bluez_agent1_proxy_get_type ())
#define ORG_BLUEZ_AGENT1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_AGENT1_PROXY, OrgBluezAgent1Proxy))
#define ORG_BLUEZ_AGENT1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_AGENT1_PROXY, OrgBluezAgent1ProxyClass))
#define ORG_BLUEZ_AGENT1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_AGENT1_PROXY, OrgBluezAgent1ProxyClass))
#define IS_ORG_BLUEZ_AGENT1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_AGENT1_PROXY))
#define IS_ORG_BLUEZ_AGENT1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_AGENT1_PROXY))

typedef struct _OrgBluezAgent1Proxy OrgBluezAgent1Proxy;
typedef struct _OrgBluezAgent1ProxyClass OrgBluezAgent1ProxyClass;
typedef struct _OrgBluezAgent1ProxyPrivate OrgBluezAgent1ProxyPrivate;

struct _OrgBluezAgent1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgBluezAgent1ProxyPrivate *priv;
};

struct _OrgBluezAgent1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_bluez_agent1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezAgent1Proxy, g_object_unref)
#endif

void org_bluez_agent1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezAgent1 *org_bluez_agent1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezAgent1 *org_bluez_agent1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_bluez_agent1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgBluezAgent1 *org_bluez_agent1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgBluezAgent1 *org_bluez_agent1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_BLUEZ_AGENT1_SKELETON (org_bluez_agent1_skeleton_get_type ())
#define ORG_BLUEZ_AGENT1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_BLUEZ_AGENT1_SKELETON, OrgBluezAgent1Skeleton))
#define ORG_BLUEZ_AGENT1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_BLUEZ_AGENT1_SKELETON, OrgBluezAgent1SkeletonClass))
#define ORG_BLUEZ_AGENT1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_BLUEZ_AGENT1_SKELETON, OrgBluezAgent1SkeletonClass))
#define IS_ORG_BLUEZ_AGENT1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_BLUEZ_AGENT1_SKELETON))
#define IS_ORG_BLUEZ_AGENT1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_BLUEZ_AGENT1_SKELETON))

typedef struct _OrgBluezAgent1Skeleton OrgBluezAgent1Skeleton;
typedef struct _OrgBluezAgent1SkeletonClass OrgBluezAgent1SkeletonClass;
typedef struct _OrgBluezAgent1SkeletonPrivate OrgBluezAgent1SkeletonPrivate;

struct _OrgBluezAgent1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgBluezAgent1SkeletonPrivate *priv;
};

struct _OrgBluezAgent1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_bluez_agent1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgBluezAgent1Skeleton, g_object_unref)
#endif

OrgBluezAgent1 *org_bluez_agent1_skeleton_new (void);


/* ---- */

#define TYPE_OBJECT (object_get_type ())
#define OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT, Object))
#define IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT))
#define OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_OBJECT, Object))

struct _Object;
typedef struct _Object Object;
typedef struct _ObjectIface ObjectIface;

struct _ObjectIface
{
  GTypeInterface parent_iface;
};

GType object_get_type (void) G_GNUC_CONST;

OrgBluezAgent1 *object_get_org_bluez_agent1 (Object *object);
OrgBluezAgent1 *object_peek_org_bluez_agent1 (Object *object);

#define TYPE_OBJECT_PROXY (object_proxy_get_type ())
#define OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_PROXY, ObjectProxy))
#define OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_PROXY))
#define IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_PROXY))

typedef struct _ObjectProxy ObjectProxy;
typedef struct _ObjectProxyClass ObjectProxyClass;
typedef struct _ObjectProxyPrivate ObjectProxyPrivate;

struct _ObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  ObjectProxyPrivate *priv;
};

struct _ObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectProxy, g_object_unref)
#endif

ObjectProxy *object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define TYPE_OBJECT_SKELETON (object_skeleton_get_type ())
#define OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_SKELETON, ObjectSkeleton))
#define OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_SKELETON))
#define IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_SKELETON))

typedef struct _ObjectSkeleton ObjectSkeleton;
typedef struct _ObjectSkeletonClass ObjectSkeletonClass;
typedef struct _ObjectSkeletonPrivate ObjectSkeletonPrivate;

struct _ObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  ObjectSkeletonPrivate *priv;
};

struct _ObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectSkeleton, g_object_unref)
#endif

ObjectSkeleton *object_skeleton_new (const gchar *object_path);
void object_skeleton_set_org_bluez_agent1 (ObjectSkeleton *object, OrgBluezAgent1 *interface_);

/* ---- */

#define TYPE_OBJECT_MANAGER_CLIENT (object_manager_client_get_type ())
#define OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClient))
#define OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_MANAGER_CLIENT))
#define IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _ObjectManagerClient ObjectManagerClient;
typedef struct _ObjectManagerClientClass ObjectManagerClientClass;
typedef struct _ObjectManagerClientPrivate ObjectManagerClientPrivate;

struct _ObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  ObjectManagerClientPrivate *priv;
};

struct _ObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectManagerClient, g_object_unref)
#endif

GType object_manager_client_get_type (void) G_GNUC_CONST;

GType object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS

#endif /* __AGENT1_H__ */
